remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
url: "https://garrettrohde.github.io/digital-cv"
include:
  - _includes

title: ""
show_title: false
logo: "/assets/images/logo.png"
show_logo: true
description: ""
show_description: false
tagcloud: "• AWS • Serverless • DevOps • CRM • Scrumban • Python • PHP • Bash • JS • TypeScript • CI/CD • GitLabs • Jenkins • MySQL • NoSQL • Full-Stack • Back-End • Front-End • API Dev • REST • SOAP •"
show_tagcloud: true
status: "Currently exploring new opportunities. Are my skills & experience a match for what your company needs? Let's connect and talk about it! (14 Feb '25)"
show_status: true
show_downloads: false

github:
  is_project_page: false

contact_info:
  location: "Yulee, Florida"
  email: "garrettdotdev@gmail.com"
  links:
    linkedin: https://linkedin.com/in/garrettrohde
    github: https://github.com/garrettdotdev
    x: https://x.com/garrettdotdev